version: '3.7'

services:
    postgres-data:
        image: postgres:alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker
        ports:
            - '5432:5432'

    gestao-pedido-service:
        image: gestao-pedido-service:${TAG:-latest}
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        ports:
            - '8080:8080'
        build:
            context: .
            dockerfile: Service/Dockerfile
        depends_on:
            - postgres-data
